# permissions for end users to edit virtoolapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: virtoolapp-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: virtool-operator
    app.kubernetes.io/part-of: virtool-operator
    app.kubernetes.io/managed-by: kustomize
  name: virtoolapp-editor-role
rules:
- apiGroups:
  - virtool.virtool.ca
  resources:
  - virtoolapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - virtool.virtool.ca
  resources:
  - virtoolapps/status
  verbs:
  - get
